apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: control-center
  name: control-center
spec:
  replicas: 1
  selector:
    matchLabels:
      service: control-center
  strategy: {}
  template:
    metadata:
      labels:
        network/kafka-network: "true"
        service: control-center
    spec:
      containers:
        - env:
            - name: CONTROL_CENTER_BOOTSTRAP_SERVERS
              value: "kafka:29092"
            - name: CONTROL_CENTER_CONNECT_CONNECT-DEFAULT_CLUSTER
              value: "connect:8083"
            - name: CONTROL_CENTER_KSQL_KSQLDB1_URL
              value: "http://ksqldb-server:8088"
            - name: CONTROL_CENTER_KSQL_KSQLDB1_ADVERTISED_URL
              value: "http://localhost:8088"
            - name: CONTROL_CENTER_SCHEMA_REGISTRY_URL
              value: "http://schema-registry:8081"
            - name: CONTROL_CENTER_REPLICATION_FACTOR
              value: "1"
            - name: CONTROL_CENTER_INTERNAL_TOPICS_PARTITIONS
              value: "1"
            - name: CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_PARTITIONS
              value: "1"
            - name: CONFLUENT_METRICS_TOPIC_REPLICATION
              value: "1"
            - name: PORT
              value: "9021"            
          image: confluentinc/cp-enterprise-control-center:7.3.1
          name: control-center
          ports:
            - containerPort: 9021
          resources: {}
      hostname: control-center
      restartPolicy: Always