apiVersion: v1
kind: Service
metadata:
  labels:
    service: control-center
  name: control-center
spec:
  ports:
    - name: "9021"
      port: 9021
      targetPort: 9021
  selector:
    service: control-center