apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer-without-exceptions
  labels:
    app: consumer-without-exceptions
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer-without-exceptions
  template:
    metadata:
      labels:
        app: consumer-without-exceptions
    spec:
      containers:
        - name: consumer-without-exceptions
          image: diandersonmendonca/avro-kafka-consumer-without-exceptions:latest
          ports:
            - containerPort: 4000
          resources:
            limits:
              cpu: 500m
              memory: 60Mi
            requests:
              cpu: 500m
              memory: 50Mi
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: docker