apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: consumer-with-exceptions
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    name: consumer-with-exceptions
    kind: Deployment
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 75